/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul_10;

/**
 *
 * @author Abel Bima Wiratama
 */
public class Program_Aritmatika extends javax.swing.JFrame {
    /**
     * Creates new form Program_Aritmatika
     */
    String jns = "";
    int jml;
    
    public Program_Aritmatika() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        bil4 = new javax.swing.JLabel();
        pilhanbil = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        jbOK = new javax.swing.JButton();
        thasil = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().setLayout(null);

        panel.setBackground(new java.awt.Color(153, 153, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel3.setText("Jumlah Bilangan");

        bil1.setText("Bilangan 1");

        bil2.setText("Bilangan 2");

        bil3.setText("Bilangan 3");

        bil4.setText("Bilangan 4");

        pilhanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        pilhanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilhanbilActionPerformed(evt);
            }
        });

        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bil1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bil2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bil3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bil4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pilhanbil, javax.swing.GroupLayout.Alignment.LEADING, 0, 125, Short.MAX_VALUE)
                    .addComponent(b1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2)
                    .addComponent(b3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b4, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thasil)
                .addContainerGap())
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jbOK)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pilhanbil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bil1)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bil2)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bil3)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bil4)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbOK)
                .addGap(18, 18, 18)
                .addComponent(thasil, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panel);
        panel.setBounds(50, 100, 330, 380);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(260, 60, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Jenis Aritmatika");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 70, 110, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PROGRAM ARITMAIKA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 20, 220, 22);

        setSize(new java.awt.Dimension(451, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void pilhanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilhanbilActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_pilhanbilActionPerformed

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        // TODO add your handling code here:
          Double hsl = 0.0;
        Double a1,a2,a3,a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1 + a2;
                thasil.setText(""+a1+"+"+a2+"="+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 + a2+ a3;
                thasil.setText(""+a1+"+"+a2+"+"+a3+"="+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+a1+"+"+a2+"+"+a3+"+"+a4+"="+hsl);
            }
        }
        else if(jns.equals("Pengurangan")){
             if(jml == 2){
                hsl = a1 - a2;
                thasil.setText(""+a1+"-"+a2+"="+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 - a2 - a3;
                thasil.setText(""+a1+"-"+a2+"-"+a3+"="+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                thasil.setText(""+a1+"-"+a2+"-"+a3+"-"+a4+"="+hsl);
            }
        }
        else if(jns.equals("Perkalian")) {
            if(jml == 2){
                hsl = a1 * a2;
                thasil.setText(""+a1+"*"+a2+"="+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 * a2 * a3;
               thasil.setText(""+a1+"*"+a2+"*"+a3+"="+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                thasil.setText(""+a1+"*"+a2+"*"+a3+"*"+a4+"="+hsl);
            }
        }
        else if(jns.equals("Pembagian")){ 
            if(jml == 2){
                hsl = a1 / a2;
                thasil.setText(""+a1+"/"+a2+"="+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 / a2 / a3;
                thasil.setText(""+a1+"/"+a2+"/"+a3+"="+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                thasil.setText(""+a1+"/"+a2+"/"+a3+"/"+a4+"="+hsl);
            }
        }
    }//GEN-LAST:event_jbOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program_Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program_Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program_Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program_Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program_Aritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbOK;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilhanbil;
    private javax.swing.JTextField thasil;
    // End of variables declaration//GEN-END:variables

    private void setJenis() {
        if (jenis.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            pilhanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            pilhanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            pilhanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            pilhanbil.setEnabled(true);
        }
    }

    private void getJumlah() {
        if(pilhanbil.getSelectedItem().equals("2")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(false);
            bil4.setVisible(false);
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(false);
            b4.setVisible(false);
            jml=2;
        }else if (pilhanbil.getSelectedItem().equals("3")){
            b1.setVisible(true);
            b2.setVisible(true);
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml=3;
        }else if(pilhanbil.getSelectedItem().equals("4")){
            b1.setVisible(true);
            b2.setVisible(true);
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml=4;
        }
    }
}
